/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      { hostname: "i.pinimg.com" },
      { hostname: "sun9-48.userapi.com" },
      { hostname: "sun9-70.userapi.com" },
      { hostname: "sun9-69.userapi.com" },
      { hostname: "sun9-46.userapi.com" },
      { hostname: "sun9-22.userapi.com" },
      { hostname: "sun9-18.userapi.com" },
      { hostname: "sun9-40.userapi.com" },
      { hostname: "sun9-41.userapi.com" },
      { hostname: "sun9-12.userapi.com" },
      { hostname: "sun9-50.userapi.com" },
      { hostname: "sun9-59.userapi.com" },
      { hostname: "sun9-60.userapi.com" },
      { hostname: "sun9-75.userapi.com" },
      { hostname: "sun9-76.userapi.com" },
      { hostname: "sun9-31.userapi.com" },
      { hostname: "sun9-41.userapi.com" },
      { hostname: "sun9-35.userapi.com" },
      { hostname: "sun9-44.userapi.com" },
      { hostname: "sun9-16.userapi.com" },
      { hostname: "sun9-6.userapi.com" },
      { hostname: "sun9-21.userapi.com" },
      { hostname: "sun9-14.userapi.com" },
      { hostname: "sun9-30.userapi.com" },
      { hostname: "sun9-64.userapi.com" },
      { hostname: "sun9-66.userapi.com" },
      { hostname: "sun9-68.userapi.com" },
      { hostname: "sun9-61.userapi.com" },
      { hostname: "mykaleidoscope.ru" },
      { hostname: "balthazar.club" },
      { hostname: "glamours.name" },
      { hostname: "dostavkatsvetov.ru" },
      { hostname: "buketn.ru" },
      { hostname: "avatars.mds.yandex.net" },
      { hostname: "dubabah.club" },
      { hostname: "sun9-79.userapi.com" },
      { hostname: "static.insales-cdn.com" },
      { hostname: "rosesmarket.ru" },
      { hostname: "sun9-79.userapi.com" },
      { hostname: "sun9-5.userapi.com" },
    ],
  },
};

export default nextConfig;
