import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import Header from "@/components/Header/Header";
import React from "react";
import Footer from "@/components/Footer";
import ru from "dayjs/locale/ru";
import isBetween from "dayjs/plugin/isBetween";
import utc from "dayjs/plugin/utc";
import duration from "dayjs/plugin/duration";
import weekday from "dayjs/plugin/weekday";
import timezone from "dayjs/plugin/timezone";
import dayjs from "dayjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

dayjs.locale(ru);
dayjs.extend(isBetween);
dayjs.extend(utc);
dayjs.extend(duration);
dayjs.extend(weekday);
dayjs.extend(timezone);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#FFD3DA] flex flex-col">
        <Providers>
          <div className="flex flex-col  min-h-[100dvh] ">
            <Header />
            <main className="flex flex-[1] pb-[80px] container mx-auto pt-[30px]">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
